version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "devops"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - tws-net
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  flask:
    build:
      context: .
    container_name: two-tier-backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: devops
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mysql
    networks:
      - tws-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      retries: 5
      interval: 10s
      start_period: 10s
      timeout: 10s

volumes:
  mysql-data:


networks:
  tws-net:
